# Generated by Django 4.2.15 on 2024-11-13 00:59
"""
This migration deletes the EconomicData model and creates a new EconomicIndicator model.
"""
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gdp', models.FloatField(blank=True, null=True)),
                ('unemployment_rate', models.FloatField(blank=True, null=True)),
                ('interest_rate', models.FloatField(blank=True, null=True)),
                ('labour_rate', models.FloatField(blank=True, null=True)),
                ('exchange_rate', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EconomicData',
        ),
    ]
