# Generated by Django 4.2.15 on 2024-11-13 03:59
"""
This migration changes the table name of the EconomicIndicator model to 'economic_indicator'.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0002_economicindicator_delete_economicdata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='economicindicator',
            table='economic_indicator',
        ),
    ]
